### ISSUE TITLE
Add some usage instructions (middleware? installed apps?)

### ISSUE THREAD

**Issue by elnygren** [namespace-ee/django-datadog-logger#1]
Thanks for this project! A suggestion how to make it more approachable:

Given that this project is listed here:
https://docs.datadoghq.com/logs/log_collection/python/?tab=jsonlogformatter#configure-your-logger

Maybe you want to add some setup instructions in the README.

So it seems like in order to use this, at least Django ->settings -> MIDDLEWARE has to be set :)

**Comment by lnagel** [comment]
Thanks for your note. Could you please check out the added quick start section and let me know your thoughts?

https://github.com/namespace-ee/django-datadog-logger#quick-start
