### ISSUE TITLE
Add description for `DJANGO_DATADOG_LOGGER_EXTRA_INCLUDE`  setting in readme/docs

### ISSUE THREAD

**Issue by evanr7** [namespace-ee/django-datadog-logger#12]
* Django DataDog Logger version: 0.5.1
* Python version: 3.10
* Operating System: Mac

### Description

Add description in readme/docs describing purpose of `DJANGO_DATADOG_LOGGER_EXTRA_INCLUDE`

Our django repository is setup to contain multiple apps, and it wasn't clear that we had to include each app-name in the regex pattern assigned to the DJANGO_DATADOG_LOGGER_EXTRA_INCLUDE setting. I had to look into library code to determine why values in the `extra` dict were not showing up in log. 

### What I Did

I had to look into  library code to figure out how to use setting `DJANGO_DATADOG_LOGGER_EXTRA_INCLUDE`
https://github.com/namespace-ee/django-datadog-logger/blob/cb0c1acb85ab1aa961a7a620d580e9c075404daa/django_datadog_logger/formatters/datadog.py#L147

**Comment by lnagel** [comment]
Thanks for reporting! Pull request is welcome :)

**Comment by lnagel** [comment]
Fixed by https://github.com/namespace-ee/django-datadog-logger/commit/dadd1834328f200bc9814bf1e0ba52eaf7331d38
