### ISSUE TITLE
ActionLogMixin doesn't support ListSerializer and list of instances

### ISSUE THREAD

**Issue by masb3** [namespace-ee/django-datadog-logger#15]
* Django DataDog Logger version: 0.6.1
* Python version: 3.11
* Operating System: MacOS

### Description
```
serializer = MySerializer(many=True)
perform_update(serializer)
```
### What I Did

```
django_datadog_logger/rest_framework/mixins.py", line 15, in get_create_log_entity
log_entity = {"pk": instance.pk}
AttributeError: 'list' object has no attribute 'pk'
```

**Comment by lnagel** [comment]
DRF normally does not allow listserializer create/updates, so i would leave this as a responsibility of the app for now.
