### ISSUE TITLE
TypeError: getattr(): attribute name must be string

### ISSUE THREAD

**Issue by oav17** [namespace-ee/django-datadog-logger#16]
* Django DataDog Logger version: 0.6.1
* Python version: 3.10
* Operating System: Linux (docker)

### Description

I just want to use `RequestIdMiddleware` to inject a request id on the logs and the `DataDogJSONFormatter` to format the logs to be readable on DataDog. RequestIdMiddleware is at the top of the Middleware list and the logs are configurated as following:

```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'default': {
            'format': '[{levelname}] [{asctime}] [{name}] {message}',
            'style': '{',
        },
        'json': {'()': 'django_datadog_logger.formatters.datadog.DataDogJSONFormatter'},
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        }
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter':  'json',
        },
        'dev_console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
    },
    'loggers': {
        'django.db.backends': {
            'level': 'DEBUG',
            'handlers': ['dev_console'],
        },
        'ddtrace': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}
```

### What I Did

When I run my django local server with `runserver` command, it starts as expected, however, once I make a request that implies a log on the process, I receive the following error:

```
--- Logging error ---
Traceback (most recent call last):
File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
msg = self.format(record)
 File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
return fmt.format(record)
 File "/usr/local/lib/python3.10/site-packages/json_log_formatter/__init__.py", line 64, in format
  json_record = self.json_record(message, extra, record)
File "/usr/local/lib/python3.10/site-packages/django_datadog_logger/formatters/datadog.py", line 131, in json_record
     log_entry_dict["usr.name"] = getattr(user, getattr(user, "USERNAME_FIELD", "username"), None)
 TypeError: getattr(): attribute name must be string
```

It seems something related with the user on the request. I making the request via POSTMAN.

**Comment by jacekbj** [comment]
@oav17 Are you using a custom authentication backend or a custom user model? That's what [Django documentation](https://docs.djangoproject.com/en/4.2/topics/auth/customizing/#django.contrib.auth.models.CustomUser.USERNAME_FIELD) mentions as a possible reason for issues with `"USERNAME_FIELD"`.

**Comment by oav17** [comment]
@jacekbj Hello, yes, that was the reason, a custom authentication was missing the `username_field` field. I was able to solve it and I forgot to close the issue.

Thank you.
