### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by johnnymetz** [namespace-ee/django-datadog-logger#24]
### Description

Can you cut a new release? I need this specific change so Datadog can generate errors in "Error Tracking" from logs: https://github.com/namespace-ee/django-datadog-logger/commit/638889b416edb74e2ffcc0d19a1dab7a504e6a58

As it stands now, Datadog is unable to generate errors in "Error Tracking" from logs.

See Datadog docs: https://docs.datadoghq.com/logs/error_tracking/backend/?tab=serilog#attributes-for-error-tracking

**Comment by lnagel** [comment]
Currently error tracking works fine for us. When we originally developed it, then for some reason it didnt work the other way around and we had to use the syslog attributes. We're currently validating the schema change in production and once confirmed will release.
