### ISSUE TITLE
Infinite loop getting request.user

### ISSUE THREAD

**Issue by jake-nz** [namespace-ee/django-datadog-logger#3]
* Django DataDog Logger version: 0.3.3
* Python version: 3.8
* Operating System: Ubuntu

### Description

`DataDogJSONFormatter` accesses `wsgi_request.user` [which can result in a `SuspiciousOperation` (checking hash from session data)](https://github.com/django/django/blob/master/django/contrib/sessions/backends/base.py#L100). Django tries to log this, which results in `DataDogJSONFormatter` being called and the loop begins again.

I believe this happened because the `SECRET_KEY` for my project changed - definitely an edge case and something that can be handled by removing sessions from DB. However, I think it's worthwhile looking into a way to prevent things which are logged during `DataDogJSONFormatter.json_record` calls from causing an infinite loop.

### What I Did

Log in to a Django app in the browser, change `settings.SECRET_KEY` attempt to access via the browser again.

**Comment by lnagel** [comment]
@jake-nz Thanks for the bug report including the mechanism to reproduce it. I will find a workaround for this situation, I've just been overwhelmed with higher priority tasks in the past few days.

**Comment by lnagel** [comment]
Fixed in 0.3.5
