### ISSUE TITLE
django_datadog_logger.wsgi.get_wsgi_request() returns None

### ISSUE THREAD

**Issue by giwrgos-skouras** [namespace-ee/django-datadog-logger#4]
* Django DataDog Logger version:  0.0.3
* Python version: 3.8
* Operating System: Ubuntu

### Description

Describe what you were trying to get done.
I am trying to get the wsgi request like this: django_datadog_logger.wsgi.get_wsgi_request()
This function seem to work fine for the past few months but now i get None when i try to get the request

### What I Did

In your code you write: 

```
from django_datadog_logger.local import Local  # NOQA

local = Local()

def get_wsgi_request():
    try:
        return local.request
    except AttributeError:
        return None
```

The problem is that local has no attribute request. Am i missing something?

**Comment by lnagel** [comment]
I'm sorry I didn't notice this at the right time.

You may have been missing the middleware install that sets the request in the local object.
